config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :articles

  get "articles" => "articles#index"
  get "articles/new" => "articles#new", as: "newarticle"
  post "articles/new" => "articles#create"
  get "articles/:id" => "articles#show"
  get "articles/:id/edit" => "articles#edit", as: "editArticle"
  put "articles/:id/edit" => "articles#update"
  post "articles/makecomment" => "makecomment"

  get "events" => "events#index"
  get "events/new" => "events#new", as: "newevent"
  post "events/new" => "events#create"
  get "events/:id" => "events#show"
  get "events/:id/edit" => "events#edit", as: "editEvent"
  put "events/:id/edit" => "events#update"
  post "events/makecomment" => "makecomment"
  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic:true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def new 
        @article = Article.new
    end
    
    def create
        article = Article.new
        article.name = params[:article][:name]
        article.content = params[:article][:content]
        if article.save
            flash[:notice] = "Article save successfully."
        else
            flash[:notice] = "Article not save."
        end
        redirect_to "/articles"
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        article = Article.find(params[:id])
        article.content = params[:article][:content]
        if article.save
            flash[:notice] = "Article updated."
        else
            flash[:notice] = "Article updated Fails. Try later."
        end
        redirect_to "/articles"
    end

    def makecomment
        @article = Article.find(params[:article_id])
        Comment.create(commentable: @article,comment_body: params[:comment],
                        user_name: params[:name])
        flash[:notice] = "you commented on an article."               
        #  p params[:name]
        #  p params[:comment]
        redirect_to "/articles"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end
    def new 
        @event = Event.new
    end
    
    def create
        event = Event.new
        event.name = params[:event][:name]
        event.description = params[:event][:description]
        if event.save
            flash[:notice] = "Event save successfully."
        else
            flash[:notice] = "Event not save."
        end
        redirect_to "/events"
    end

    def show
        @event = Event.find(params[:id])
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        event = Event.find(params[:id])
        event.name = params[:event][:name]
        event.description = params[:event][:description]
        if event.save
            flash[:notice] = "Event updated."
        else
            flash[:notice] = "Event updated Fails. Try later."
        end
        redirect_to "/events"
    end

    def makecomment
        @event = Event.find(params[:event_id])
        Comment.create(commentable: @event,comment_body: params[:comment],
                        user_name: params[:name])
        flash[:notice] = "you commented on an event."               
        #  p params[:name]
        #  p params[:comment]
        redirect_to "/events"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/articles/edit.html.erb
<div class="container">
    <div>   
    <h3 class="text-danger">Edit This Article :</h3>
    <hr style="border: 1px solid red;">
    </div>
    <%= form_for @article, :method => "put", :html => {:class => "form-horizontal center"} do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Posted By:", class: "col-md-3 text-right text-info h4 control-label" %>
            <div class="col-md-6">
            <%= f.text_field :name, value: @article.name,:readonly=> true, class: "form-control", :required=>true %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :content, "Article Content:", class: "col-md-3 text-right text-info h4 
                                                            control-label" %>
            <div class="col-md-6">
            <%= f.text_area :content, value: @article.content, class: "form-control", required: true %>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4" style="margin-left: 33%;">
                <%= f.submit "Update", class: "btn btn-default btn-primary" %> 
                <%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, "/articles" %>
            </div>
        </div>
    <% end %>
    </div>
</div>

app/views/articles/index.html.erb
<%= link_to "Show me Events", "events"%>
<div>
    <h5> Total Articles Are: 
        <label style="color:#ba2121;">
            <strong>
            <%= @articles.count %>
            </strong>
        </label
    </h5>
</div>
<% if flash[:notice] %>
    <div class="h5" style="padding: 5px 10px; color: #d13436; border: 1px solid #d13436;
                    border-radius: 5px;">	
        <%= flash[:notice] %>
    </div>
<% end %>
<%= link_to "<button class='btn btn-danger'>Add Article</button>".html_safe,
                     newarticle_path %>
<hr style="border: 1px solid grey">
<% @articles.each do |article| %>
    <h3  style="margin-bottom: 0px;"><%= article.id %>: <%= article.content %></h3>
    <span style="color: #3c0d5b;">Posted By :-<%= article.name %></span>

    <div>
        <%= link_to "<button class='btn btn-success'>Edit Article</button>".html_safe,
                     edit_article_path(article) %>
    </div>
    <div class="container" style="margin-top: 10px;">
        <div style="border: 1px solid grey;padding: 10px;border-radius: 10px;z-index:1;
                        box-shadow: 4px 4px 12px 0 grey;margin-bottom:10px;">
        <%= form_tag "/articles/makecomment", method: "post",:class=>"form-inline" do %>
            <label class="text-primary"> Comment Here:</label>            
            <%= hidden_field_tag :article_id, article.id %>
            <div class="form-group" style="margin: 0px 10px;"> 
                <div>
                    <%= text_field_tag :name, nil,:class=>'form-control',
                                :placeholder=>"Enter Your name" ,:required=>true %>
                </div>
            </div>

            <div class="form-group">
                <div>
                    <%= text_area_tag :comment,nil ,:class=>'form-control',:rows => 1,cols: 50,
                            :placeholder=>"Enter Your Comment" ,:required=>true %>	  	
                </div>
            </div>
            <div class="form-group" style="margin: 0px 10px;">
                <div>
                    <%= submit_tag "Comment", class: "btn btn-danger", title: "Click to Comment" %>
                </div>
            </div>
        <% end %>
        </div>
        <!--
            comment div
        -->

        <div class="container well">
            <% comments = article.comments.order(created_at: :desc) %>
            <% if comments.count == 0 %>
                <div class="panel-body">
                    <p>There is no comments on this article.</p>
                </div>

            <% else %>
                <div class="panel-heading">
                    <h5 class="text-danger">Comments on this "Article":-  </h5>
                </div>
                <% flag = 0 %>
                <% comments.each do |comment| %>
                    <% flag = flag+1 %>
                    <div class="panel-body">
                        <p style="color: #13367c;margin-bottom: 2px;"><%= flag %>: <%= comment.comment_body %></p>
                        <span style="color: #cc3914;"> ---By: <%= comment.user_name %>
                    </div>
                    <hr style="border: 0.5px solid red;">
                <% end%>
            <% end %>
        </div>
    </div>

    
    <hr style="border: 1px solid #63105d;">
<% end %>


<script>
    $("document").ready(function(){
        function call(){
            alert(Called);
        }
    });
</script>

app/views/articles/new.html.erb
<div class="container">
    <div>   
        <h3 style="color: #3c0d5b;">Add New Article :</h3>
        <hr style="border: 1px solid red;">
    </div>
    <%= form_for :article, :method => "post", :html => {:class => "form-horizontal center"} do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Posting By:", class: "col-md-3 text-danger text-right h5 control-label" %>
            <div class="col-md-6">
            <%= f.text_field :name, class: "form-control", :placeholder=> "Enter Your Name",
                             :required=>true %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :content, "Article Content:", class: "col-md-3 text-danger text-right
                                                                h5 control-label" %>
            <div class="col-md-6">
            <%= f.text_area :content, class: "form-control",:placeholder=> "Write an article here",
                     required: true %>
            </div>
        </div>
        <div class="form-group row" style=" margin-left:33%;">
            <%= f.submit "Submit", class: "btn btn-default btn-primary" %> 
            <%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, "/articles" %>
        </div>
    <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<p><%= @article.content %></p>
<span>--<%= @article.name %><span> 
<div>
    
</div>
<hr>

app/views/events/edit.html.erb
<div class="container">

    <div>   
    <h3 class="text-danger">Edit This Event :</h3>
    <hr style="border: 1px solid red;">
    </div>
    <%= form_for @event, :method => "put", :html => {:class => "form-horizontal center"} do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Event Name:", class: "col-md-3 text-right text-info h4 
                                                        control-label" %>
            <div class="col-md-6">
            <%= f.text_field :name, value: @event.name, class: "form-control", :required=>true %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :description, "Event Description:", class: "col-md-3 text-right text-info h4 control-label" %>
            <div class="col-md-6">
            <%= f.text_area :description, value: @event.description, class: "form-control", required: true %>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-4" style="margin-left: 33%;">
                <%= f.submit "Update", class: "btn btn-default btn-primary" %> 
                <%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, "/events" %>
            </div>
        </div>
    <% end %>
</div>

app/views/events/index.html.erb
<%= link_to "Show me Articles", articles_path%>
<div>
    <h5> Total Events Are:
        <label  style="color:#ba2121;">
            <strong>
                <%= @events.count %>
            </strong>
        </label>
    </h3>
</div>
<% if flash[:notice] %>
    <div class="h5" style="padding: 5px 10px; color: #d13436; border: 1px solid #d13436;border-radius: 5px;">	
        <%= flash[:notice] %>
    </div>
<% end %>
<%= link_to "<button class='btn btn-danger'>Add Event</button>".html_safe, newevent_path %>
<hr style="border: 1px solid grey">
<% @events.each do |event| %>
    <h3 style="margin-bottom: 0px;"><%= event.id %>: <%= event.name %> </h3>
    <span style="color: #3c0d5b;">Description:- <%= event.description%></span>
    <div>
        <%= link_to "<button class='btn btn-success'>Edit Event</button>".html_safe, edit_event_path(event) %>
    </div>


    <div class="container" style="margin-top: 10px;">
        <div style="border: 1px solid grey;padding: 10px;border-radius: 10px;z-index:1;
        box-shadow: 4px 4px 12px 0 grey;margin-bottom:10px;">
            <%= form_tag "/events/makecomment", method: "post",:class=>"form-inline" do %>
                <h5 class="text-primary"> Comment Here:</h5>            
                <%= hidden_field_tag :event_id, event.id %>
                <div class="form-group" style="margin: 0px 10px;">
                    <div>
                        <%= text_field_tag :name, nil,:class=>'form-control',
                                    :placeholder=>"Enter Your name" ,:required=>true %>
                    </div>
                </div>

                <div class="form-group">
                    <div>
                        <%= text_area_tag :comment,nil ,:class=>'form-control',:rows=> 1,:cols=> 50,
                                :placeholder=>"Enter Your Comment" ,:required=>true %>	  	
                    </div>
                </div>
                <div class="form-group" style="margin: 0px 10px;">
                    <div>
                        <%= submit_tag "Comment", class: "btn btn-danger", title: "Click to Comment" %>
                    </div>
                </div>
            <% end %>
        </div>
        <!--
            comment div
        -->

        <div class="container well">
            <% comments = event.comments.order(created_at: :desc) %>
            <% if comments.count == 0 %>
                <div class="panel-body">
                    <p>There is no comments on this Event.</p>
                </div>

            <% else %>
                <div class="panel-heading">
                    <h5 class="text-danger">Comments on this "Event":-</h5>
                </div>
                <% flag = 0 %>
                <% comments.each do |comment| %>
                    <% flag = flag+1 %>
                    <div class="panel-body">
                        <p style="color: #13367c;margin-bottom: 2px;"><%= flag %>: <%= comment.comment_body %></p>
                        <span style="color: #cc3914;"> ---By: <%= comment.user_name %>
                        <hr style="border: 0.5px solid red;">
                    </div>
                <% end%>
            <% end %>
        </div>
    </div>
    <hr style="border: 1px solid #63105d;">
<% end %>

app/views/events/new.html.erb
<div class="container">
    <div>   
        <h3 style="color: #3c0d5b;">Add New Article :</h3>
        <hr style="border: 1px solid red;">
    </div>
    <%= form_for :event, :method => "post", :html => {:class => "form-horizontal center"} do |f| %>
        <div class="form-group row">
            <%= f.label :name, "Event Name:", class: "col-md-3 text-danger text-right h5 control-label" %>
            <div class="col-md-6">
            <%= f.text_field :name, class: "form-control",:placeholder=>"Enter event Name",
                             :required=>true %>
            </div>
        </div>
        <div class="form-group row">
            <%= f.label :content, "Event Description:", class: "col-md-3 text-danger text-right h5
                                     control-label" %>
            <div class="col-md-6">
            <%= f.text_area :description, class: "form-control",:placeholder=>"Describe about event",
                             required: true %>
            </div>
        </div>
        <div class="form-group row">
            <div style="margin-left: 33%;">
                <%= f.submit "Submit", class: "btn btn-default btn-primary" %> 
                <%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, "/events" %>
            </div>
        </div>
    <% end %>
</div>


 

app/views/events/show.html.erb
<span><%= @event.name %><span> 
<p><%= @event.description %></p>
<div>
    <%= link_to "Back", "/events" %>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolyAssociation</title>
    <%= csrf_meta_tags %>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>